# Generated by Django 5.0.6 on 2025-06-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0005_investir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(auto_now=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descricao', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=10)),
                ('Conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
