# Generated by Django 5.0.6 on 2024-06-04 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conta', models.IntegerField(blank=True)),
                ('Saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Img', models.ImageField(upload_to='imagem/%d/%m/%y')),
                ('Nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
