# Generated by Django 5.0.6 on 2024-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0003_caxinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='caxinha',
            name='Caxinha',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
