# Generated by Django 5.0.6 on 2025-06-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0007_alter_movimentacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas',
            name='Data',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
