# Generated by Django 5.0.6 on 2025-06-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0008_contas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='Data',
        ),
        migrations.AddField(
            model_name='contas',
            name='Data_transacao',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
