# Generated by Django 5.0.6 on 2025-06-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0009_remove_contas_data_contas_data_transacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contas',
            name='Data_transacao',
        ),
    ]
