# Generated by Django 5.0.6 on 2025-06-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heart', '0010_remove_contas_data_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='Descricao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='Tipo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
